import type { FxPreset } from "./types";

/**
 * Melee and weapon attacks. Directional presets strike toward the right:
 * use the `rotation` prop (radians) to aim them, or `scale={[-1, 1]}` to mirror.
 */
export const ATTACK_FX_PRESETS = {
  swordSlash: {
    duration: 220,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "slash",
          lifetime: 210,
          rotation: -35,
          rotationSpeed: 420,
          color: ["#ffffff", "#bfe6ff"],
          alpha: [1, 0.9, 0],
          scale: [0.75, 0.95],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 25,
        burst: 1,
        particle: {
          shape: "slash",
          lifetime: 230,
          rotation: -45,
          rotationSpeed: 380,
          color: "#6fb8ff",
          alpha: [0.55, 0],
          scale: [0.62, 0.8],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 60,
        burst: 12,
        x: 46,
        spreadY: 26,
        angle: [-35, 35],
        speed: [160, 380],
        drag: 4,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [140, 300],
          color: ["#ffffff", "#9fd8ff"],
          alpha: [1, 0],
          scale: [0.24, 0],
          blendMode: "add",
        },
      },
    ],
  },
  heavySlash: {
    duration: 320,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "slash",
          lifetime: 300,
          rotation: -50,
          rotationSpeed: 360,
          color: ["#ffffff", "#ffd36d", "#ff6a1f"],
          alpha: [1, 1, 0],
          scale: [1.05, 1.35],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 30,
        burst: 1,
        particle: {
          shape: "slash",
          lifetime: 320,
          rotation: -62,
          rotationSpeed: 330,
          color: "#ff8a3d",
          alpha: [0.7, 0],
          scale: [0.9, 1.15],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 80,
        burst: 1,
        x: 60,
        particle: {
          shape: "ring",
          lifetime: 280,
          color: "#ffe2a8",
          alpha: [0.9, 0],
          scale: [0.4, 2.4],
          scaleX: 0.45,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 70,
        burst: 22,
        x: 60,
        spreadY: 36,
        angle: [-45, 45],
        speed: [220, 520],
        drag: 4,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [180, 380],
          color: ["#ffffff", "#ffb347"],
          alpha: [1, 0],
          scale: [0.3, 0],
          blendMode: "add",
        },
      },
      {
        delay: 70,
        burst: 8,
        x: 50,
        angle: [-20, 20],
        speed: [500, 800],
        drag: 5,
        particle: {
          shape: "streak",
          align: "velocity",
          lifetime: [140, 240],
          color: "#fff3d6",
          alpha: [0.9, 0],
          scale: 0.8,
          scaleX: [0.4, 1.4],
          blendMode: "add",
        },
      },
    ],
  },
  crossSlash: {
    duration: 320,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "slash",
          lifetime: 230,
          rotation: -80,
          rotationSpeed: 300,
          color: ["#ffffff", "#c9f0ff"],
          alpha: [1, 0.9, 0],
          scale: [0.8, 0.95],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 110,
        burst: 1,
        particle: {
          shape: "slash",
          lifetime: 230,
          rotation: 100,
          rotationSpeed: -300,
          color: ["#ffffff", "#c9f0ff"],
          alpha: [1, 0.9, 0],
          scale: [0.8, 0.95],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 150,
        burst: 1,
        particle: {
          shape: "flare",
          lifetime: 260,
          color: ["#ffffff", "#a8e4ff"],
          alpha: [1, 0],
          scale: [1.2, 2.8],
          rotation: 45,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 150,
        burst: 20,
        radius: 4,
        direction: "outward",
        speed: [200, 420],
        drag: 4,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [160, 340],
          color: ["#ffffff", "#7fd0ff"],
          alpha: [1, 0],
          scale: [0.26, 0],
          blendMode: "add",
        },
      },
    ],
  },
  spinSlash: {
    duration: 420,
    emitters: [
      {
        burst: 3,
        particle: {
          shape: "slash",
          lifetime: [340, 400],
          rotation: [0, 360],
          rotationSpeed: 900,
          color: ["#ffffff", "#bff5e0"],
          alpha: [0, 1, 0],
          scale: [0.7, 1],
          blendMode: "add",
        },
      },
      {
        burst: 30,
        radius: [30, 70],
        ellipse: 0.6,
        direction: "tangent",
        speed: [200, 320],
        orbit: 420,
        drag: 2,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [240, 420],
          color: ["#ffffff", "#9ff0d0"],
          alpha: [0, 1, 0],
          scale: [0.3, 0.1],
          blendMode: "add",
        },
      },
      {
        burst: 12,
        radius: [10, 40],
        ellipse: 0.5,
        direction: "outward",
        speed: [40, 110],
        drag: 1.5,
        particle: {
          shape: "softCircle",
          lifetime: [400, 700],
          color: "#cfe7dc",
          alpha: [0, 0.35, 0],
          scale: [0.5, 1.4],
        },
      },
    ],
  },
  pierce: {
    duration: 240,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "streak",
          anchor: { x: 0, y: 0.5 },
          lifetime: 200,
          color: ["#ffffff", "#bfe6ff"],
          alpha: [1, 1, 0],
          scale: 1.4,
          scaleX: [0.3, 1.5, 1.7],
          scaleY: [3, 1.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 60,
        burst: 1,
        x: 190,
        particle: {
          shape: "ring",
          lifetime: 240,
          color: "#dff4ff",
          alpha: [0.95, 0],
          scale: [0.3, 1.8],
          scaleX: 0.4,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 60,
        burst: 14,
        x: 190,
        angle: [-25, 25],
        speed: [220, 460],
        drag: 4,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [140, 300],
          color: ["#ffffff", "#8fd3ff"],
          alpha: [1, 0],
          scale: [0.24, 0],
          blendMode: "add",
        },
      },
    ],
  },
  clawStrike: {
    duration: 260,
    emitters: [
      {
        delay: 0,
        burst: 1,
        x: -14,
        y: -22,
        particle: {
          shape: "streak",
          lifetime: 220,
          rotation: 58,
          color: ["#ffffff", "#ff6a6a", "#b3132a"],
          alpha: [1, 1, 0],
          scale: 1.1,
          scaleX: [0.2, 1.3, 1.4],
          scaleY: [2.4, 1.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 35,
        burst: 1,
        x: 0,
        y: 0,
        particle: {
          shape: "streak",
          lifetime: 220,
          rotation: 58,
          color: ["#ffffff", "#ff6a6a", "#b3132a"],
          alpha: [1, 1, 0],
          scale: 1.1,
          scaleX: [0.2, 1.3, 1.4],
          scaleY: [2.4, 1.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 70,
        burst: 1,
        x: 14,
        y: 22,
        particle: {
          shape: "streak",
          lifetime: 220,
          rotation: 58,
          color: ["#ffffff", "#ff6a6a", "#b3132a"],
          alpha: [1, 1, 0],
          scale: 1.1,
          scaleX: [0.2, 1.3, 1.4],
          scaleY: [2.4, 1.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 90,
        burst: 14,
        radius: 6,
        direction: "outward",
        speed: [140, 300],
        drag: 4,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [160, 320],
          color: ["#ffffff", "#ff4d4d"],
          alpha: [1, 0],
          scale: [0.22, 0],
          blendMode: "add",
        },
      },
    ],
  },
  groundSlam: {
    duration: 520,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 200,
          color: ["#ffffff", "#ffd9a0"],
          alpha: [0.9, 0],
          scale: [1, 3],
          scaleY: 0.5,
          blendMode: "add",
        },
      },
      {
        burst: 1,
        burstCount: 2,
        burstInterval: 110,
        particle: {
          shape: "ring",
          lifetime: 460,
          color: "#ffe6bf",
          alpha: [0.9, 0],
          scale: [0.5, 4.4],
          scaleY: 0.38,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 24,
        spreadX: 24,
        angle: [-160, -20],
        speed: [220, 460],
        gravity: 1100,
        particle: {
          shape: "square",
          lifetime: [520, 820],
          color: ["#c2a47a", "#5c4a34"],
          alpha: [1, 1, 0],
          scale: [0.34, 0.2],
          rotationSpeed: [-600, 600],
        },
      },
      {
        burst: 20,
        radius: [10, 30],
        ellipse: 0.35,
        direction: "outward",
        speed: [120, 260],
        drag: 3,
        particle: {
          shape: "softCircle",
          lifetime: [600, 1100],
          color: "#b39a78",
          alpha: [0.5, 0],
          scale: [0.5, 1.9],
          scaleY: 0.7,
          rotationSpeed: [-40, 40],
        },
      },
      {
        burst: 14,
        radius: 12,
        ellipse: 0.35,
        direction: "outward",
        speed: [600, 900],
        drag: 6,
        particle: {
          shape: "streak",
          align: "velocity",
          lifetime: [180, 300],
          color: "#fff0d0",
          alpha: [0.8, 0],
          scale: 0.7,
          blendMode: "add",
        },
      },
    ],
  },
  comboHits: {
    duration: 520,
    emitters: [
      {
        burst: 1,
        burstCount: 5,
        burstInterval: 95,
        spreadX: 26,
        spreadY: 22,
        particle: {
          shape: "slash",
          lifetime: 160,
          rotation: [0, 360],
          rotationSpeed: 500,
          color: ["#ffffff", "#ffe08a"],
          alpha: [1, 0],
          scale: [0.45, 0.6],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 8,
        burstCount: 5,
        burstInterval: 95,
        spreadX: 22,
        spreadY: 18,
        angle: [0, 360],
        speed: [140, 320],
        drag: 4,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [120, 260],
          color: ["#ffffff", "#ffa94d"],
          alpha: [1, 0],
          scale: [0.22, 0],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        burstCount: 5,
        burstInterval: 95,
        spreadX: 20,
        spreadY: 16,
        particle: {
          shape: "softCircle",
          lifetime: 120,
          color: "#fff4d0",
          alpha: [0.9, 0],
          scale: [0.4, 1.3],
          blendMode: "add",
        },
      },
    ],
  },
} satisfies Record<string, FxPreset>;

/**
 * Big cinematic effects for limit breaks, ultimates and summons.
 * They cover a large area: place them at the target, often behind a flash.
 */
export const EPIC_FX_PRESETS = {
  limitBurst: {
    duration: 700,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 380,
          color: ["#ffffff", "#ffe8a0"],
          alpha: [1, 0],
          scale: [2, 10],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 44,
        radius: [20, 60],
        direction: "outward",
        speed: [900, 1700],
        drag: 1.6,
        particle: {
          shape: "streak",
          align: "velocity",
          lifetime: [260, 520],
          color: ["#ffffff", "#ffe27a", "#ff8a3d"],
          alpha: [1, 0],
          scale: 1,
          scaleX: [0.6, 3.2],
          scaleY: [2.2, 1],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        burstCount: 3,
        burstInterval: 120,
        particle: {
          shape: "prism",
          lifetime: 620,
          color: "#ffffff",
          alpha: [1, 0],
          scale: [0.4, 5.5],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 14,
        particle: {
          shape: "beam",
          anchor: { x: 0.5, y: 1 },
          lifetime: [320, 520],
          rotation: [0, 360],
          color: ["#fffbe6", "#ffd36d"],
          alpha: [0.9, 0],
          scale: 1,
          scaleX: [1.2, 0.2],
          scaleY: [0.4, 3.4],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 120,
        burst: 26,
        radius: [30, 220],
        particle: {
          shape: "flare",
          lifetime: [300, 700],
          color: ["#ffffff", "#ffe89a"],
          alpha: [0, 1, 0],
          scale: [0.2, 0.7, 0.1],
          rotationSpeed: [-120, 120],
          blendMode: "add",
        },
      },
    ],
  },
  holyPillar: {
    duration: 1300,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "beam",
          anchor: { x: 0.5, y: 1 },
          lifetime: 1250,
          color: ["#ffffff", "#fff1b0", "#ffd36d"],
          alpha: [0, 1, 1, 0],
          scale: 1,
          scaleX: [0.2, 2.6, 2.2, 0.1],
          scaleY: [0.6, 4, 4.2, 4.4],
          blendMode: "add",
        },
      },
      {
        delay: 80,
        burst: 1,
        particle: {
          shape: "beam",
          anchor: { x: 0.5, y: 1 },
          lifetime: 1100,
          color: "#ffffff",
          alpha: [0, 1, 0.8, 0],
          scale: 1,
          scaleX: [0.1, 0.9, 0.7, 0.05],
          scaleY: [0.6, 4, 4.2],
          blendMode: "add",
        },
      },
      {
        delay: 120,
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 500,
          color: ["#ffffff", "#fff4c8"],
          alpha: [1, 0],
          scale: [1.5, 8],
          scaleY: 0.55,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 120,
        burst: 1,
        burstCount: 3,
        burstInterval: 180,
        particle: {
          shape: "ring",
          lifetime: 700,
          color: "#ffe9a8",
          alpha: [0.9, 0],
          scale: [0.6, 5],
          scaleY: 0.35,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 120,
        rate: 70,
        duration: 900,
        radius: [0, 50],
        ellipse: 0.35,
        angle: -90,
        speed: [180, 420],
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [500, 900],
          color: ["#ffffff", "#ffe89a"],
          alpha: [0, 1, 0],
          scale: [0.32, 0.12],
          blendMode: "add",
        },
      },
      {
        delay: 200,
        burst: 30,
        radius: [20, 160],
        y: -120,
        angle: [80, 100],
        speed: [20, 70],
        particle: {
          shape: "flare",
          lifetime: [700, 1300],
          color: ["#ffffff", "#fff1b0"],
          alpha: [0, 1, 0],
          scale: [0.15, 0.5, 0.05],
          rotationSpeed: [-120, 120],
          blendMode: "add",
        },
      },
    ],
  },
  crystalBurst: {
    duration: 700,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 520,
          color: ["#e6fdff", "#3fd0ff"],
          alpha: [0.95, 0],
          scale: [1, 4.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 26,
        burstCount: 2,
        burstInterval: 160,
        radius: 10,
        direction: "outward",
        speed: [260, 560],
        drag: 3.2,
        particle: {
          shape: "diamond",
          align: "velocity",
          lifetime: [520, 900],
          color: ["#ffffff", "#8ff0ff", "#1f8fe6"],
          alpha: [1, 1, 0],
          scale: [1, 0.55],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        burstCount: 2,
        burstInterval: 160,
        particle: {
          shape: "ring",
          lifetime: 520,
          color: "#9ff2ff",
          alpha: [1, 0],
          scale: [0.4, 4],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        rate: 80,
        duration: 600,
        radius: [10, 110],
        angle: [-110, -70],
        speed: [30, 120],
        particle: {
          shape: "flare",
          lifetime: [400, 900],
          color: ["#ffffff", "#7fe8ff"],
          alpha: [0, 1, 0],
          scale: [0.1, 0.4, 0.05],
          rotationSpeed: [-180, 180],
          blendMode: "add",
        },
      },
      {
        burst: 30,
        radius: [0, 40],
        direction: "outward",
        speed: [60, 180],
        drag: 1.5,
        gravity: -60,
        particle: {
          shape: "circle",
          lifetime: [600, 1100],
          color: ["#ffffff", "#5fd8ff"],
          alpha: [1, 0],
          scale: [0.12, 0.04],
          blendMode: "add",
        },
      },
    ],
  },
  chargeOrb: {
    duration: 1300,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 1300,
          color: ["#fff6d8", "#ffd36d", "#ffffff"],
          alpha: [0, 0.9, 1, 1, 0],
          scale: [0.2, 0.8, 1.1, 1.6, 4],
          blendMode: "add",
        },
      },
      {
        rate: 60,
        duration: 1000,
        radius: [110, 170],
        direction: "inward",
        speed: [180, 260],
        orbit: 120,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [500, 650],
          color: ["#fff6d8", "#ffcf5a"],
          alpha: [0, 1, 0.2],
          scale: [0.3, 0.08],
          blendMode: "add",
        },
      },
      {
        rate: 20,
        duration: 1000,
        radius: [140, 200],
        direction: "inward",
        speed: [500, 700],
        particle: {
          shape: "streak",
          align: "velocity",
          lifetime: [200, 300],
          color: "#fff3cc",
          alpha: [0, 0.8, 0],
          scale: 0.7,
          blendMode: "add",
        },
      },
      {
        delay: 1050,
        burst: 1,
        particle: {
          shape: "flare",
          lifetime: 320,
          color: "#ffffff",
          alpha: [1, 0],
          scale: [1, 5],
          rotation: 45,
          rotationSpeed: 90,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 1050,
        burst: 1,
        particle: {
          shape: "prism",
          lifetime: 420,
          color: "#ffffff",
          alpha: [1, 0],
          scale: [0.3, 3.5],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  summonSigil: {
    duration: 1800,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "sigil",
          lifetime: 1800,
          color: ["#bfefff", "#6fb8ff", "#b58cff"],
          alpha: [0, 1, 1, 1, 0],
          scale: [0.3, 1.6, 1.7, 1.7, 1.9],
          perspective: 0.45,
          rotationSpeed: 45,
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        delay: 150,
        burst: 1,
        particle: {
          shape: "sigil",
          lifetime: 1550,
          color: ["#e6f8ff", "#8fd0ff"],
          alpha: [0, 0.8, 0.8, 0],
          scale: [0.2, 0.9, 1],
          perspective: 0.45,
          rotation: 22,
          rotationSpeed: -70,
          blendMode: "add",
        },
      },
      {
        delay: 250,
        rate: 50,
        duration: 1300,
        radius: 100,
        innerRadius: 92,
        ellipse: 0.45,
        orbit: 45,
        angle: -90,
        speed: [60, 160],
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [500, 900],
          color: ["#ffffff", "#8fd0ff"],
          alpha: [0, 1, 0],
          scale: [0.28, 0.1],
          blendMode: "add",
        },
      },
      {
        delay: 400,
        burst: 8,
        radius: 72,
        innerRadius: 72,
        ellipse: 0.45,
        particle: {
          shape: "beam",
          anchor: { x: 0.5, y: 1 },
          lifetime: [900, 1200],
          color: ["#e6f8ff", "#6fb8ff"],
          alpha: [0, 0.8, 0],
          scale: 1,
          scaleX: [0.2, 0.5, 0.1],
          scaleY: [0.3, 1.6, 2],
          blendMode: "add",
        },
      },
      {
        delay: 300,
        rate: 30,
        duration: 1200,
        radius: [0, 80],
        ellipse: 0.45,
        angle: -90,
        speed: [20, 60],
        particle: {
          shape: "flare",
          lifetime: [600, 1100],
          color: "#dff4ff",
          alpha: [0, 1, 0],
          scale: [0.1, 0.35, 0.05],
          blendMode: "add",
        },
      },
    ],
  },
  shockwave: {
    duration: 600,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 220,
          color: "#ffffff",
          alpha: [1, 0],
          scale: [1, 4],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        burstCount: 3,
        burstInterval: 90,
        particle: {
          shape: "ring",
          lifetime: 600,
          color: ["#ffffff", "#bfe0ff"],
          alpha: [1, 0],
          scale: [0.4, 7],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 36,
        radius: 20,
        direction: "outward",
        speed: [900, 1400],
        drag: 3,
        particle: {
          shape: "streak",
          align: "velocity",
          lifetime: [220, 380],
          color: "#eef6ff",
          alpha: [0.9, 0],
          scale: 0.9,
          scaleX: [0.5, 2],
          blendMode: "add",
        },
      },
    ],
  },
} satisfies Record<string, FxPreset>;
