import type { FxPreset } from "./types";

/**
 * RPG spell effects. Every preset is a one-shot (use `trigger` or `autostart`)
 * unless it is listed in `AURA_FX_PRESETS`.
 *
 * All of them can be recolored with the `color` / `hueShift` props or `customizeFx()`.
 */
export const MAGIC_FX_PRESETS = {
  fireball: {
    duration: 420,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 260,
          color: ["#ffffff", "#ffb347"],
          alpha: [1, 0],
          scale: [0.8, 3.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 26,
        angle: [0, 360],
        speed: [60, 210],
        drag: 3,
        gravity: -70,
        particle: {
          shape: "softCircle",
          lifetime: [320, 680],
          color: ["#fff3b0", "#ff7a1a", "#b3200f"],
          alpha: [0.95, 0.7, 0],
          scale: [0.45, 1.25],
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        burst: 18,
        angle: [0, 360],
        speed: [140, 340],
        drag: 1.6,
        gravity: -40,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [380, 820],
          color: ["#ffe08a", "#ff4d1a"],
          alpha: [1, 0],
          scale: [0.16, 0],
          blendMode: "add",
        },
      },
      {
        delay: 140,
        burst: 10,
        angle: [-150, -30],
        speed: [20, 60],
        spreadX: 14,
        gravity: -30,
        particle: {
          shape: "softCircle",
          lifetime: [700, 1200],
          color: ["#5a4a42", "#2a2a2a"],
          alpha: [0, 0.32, 0],
          scale: [0.6, 1.9],
          rotationSpeed: [-40, 40],
          ease: "outQuad",
        },
      },
    ],
  },
  frostNova: {
    duration: 500,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "ring",
          lifetime: 460,
          color: ["#ffffff", "#7fd8ff"],
          alpha: [0.95, 0],
          scale: [0.3, 3.4],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 22,
        radius: 8,
        direction: "outward",
        speed: [170, 320],
        drag: 3.5,
        particle: {
          shape: "diamond",
          align: "velocity",
          lifetime: [480, 820],
          color: ["#ffffff", "#8fe3ff", "#3a8dde"],
          alpha: [1, 1, 0],
          scale: [0.55, 0.3],
          blendMode: "add",
        },
      },
      {
        burst: 12,
        radius: [0, 20],
        direction: "outward",
        speed: [20, 60],
        particle: {
          shape: "softCircle",
          lifetime: [700, 1150],
          color: "#cfefff",
          alpha: [0, 0.35, 0],
          scale: [0.6, 1.7],
          blendMode: "add",
        },
      },
      {
        delay: 120,
        burst: 10,
        radius: [12, 60],
        particle: {
          shape: "flare",
          lifetime: [300, 700],
          color: ["#ffffff", "#bff0ff"],
          alpha: [0, 1, 0],
          scale: [0.1, 0.4, 0.05],
          rotationSpeed: [-90, 90],
          blendMode: "add",
        },
      },
    ],
  },
  iceSpikes: {
    duration: 420,
    emitters: [
      {
        burst: 7,
        burstCount: 3,
        burstInterval: 90,
        spreadX: 40,
        spreadY: 10,
        angle: [-100, -80],
        speed: [220, 380],
        drag: 6,
        particle: {
          shape: "diamond",
          align: "velocity",
          lifetime: [520, 760],
          color: ["#ffffff", "#9fe8ff", "#4a9fe6"],
          alpha: [1, 1, 0],
          scale: [0.9, 0.7],
          blendMode: "add",
        },
      },
      {
        burst: 16,
        spreadX: 44,
        spreadY: 6,
        angle: [-160, -20],
        speed: [30, 90],
        drag: 2,
        particle: {
          shape: "softCircle",
          lifetime: [600, 1000],
          color: "#dff6ff",
          alpha: [0, 0.4, 0],
          scale: [0.4, 1.3],
          blendMode: "add",
        },
      },
    ],
  },
  thunderStrike: {
    duration: 360,
    emitters: [
      {
        burst: 22,
        burstCount: 3,
        burstInterval: 80,
        y: -150,
        spreadX: 7,
        spreadY: 150,
        particle: {
          shape: "spark",
          lifetime: [70, 160],
          rotation: [70, 110],
          color: ["#ffffff", "#a8c8ff"],
          alpha: [1, 0],
          scale: [0.6, 0.3],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        burstCount: 3,
        burstInterval: 80,
        particle: {
          shape: "softCircle",
          lifetime: 240,
          color: ["#ffffff", "#6f8dff"],
          alpha: [1, 0],
          scale: [1.2, 3],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 26,
        angle: [-180, 0],
        speed: [160, 400],
        gravity: 700,
        drag: 1,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [240, 540],
          color: ["#ffffff", "#7fb2ff"],
          alpha: [1, 0],
          scale: [0.22, 0.05],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        particle: {
          shape: "ring",
          lifetime: 320,
          color: "#bcd4ff",
          alpha: [0.9, 0],
          scale: [0.3, 2.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  holyLight: {
    duration: 600,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 800,
          color: "#fff6c8",
          alpha: [0, 0.6, 0],
          scale: [1.2, 3.2],
          blendMode: "add",
        },
      },
      {
        rate: 45,
        duration: 520,
        spreadX: 26,
        spreadY: 6,
        angle: -90,
        speed: [140, 260],
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [500, 900],
          color: ["#ffffff", "#ffe89a"],
          alpha: [0, 0.9, 0],
          scale: [0.34, 0.12],
          blendMode: "add",
        },
      },
      {
        burst: 14,
        radius: [10, 42],
        angle: -90,
        speed: [10, 34],
        particle: {
          shape: "flare",
          lifetime: [500, 1000],
          color: ["#ffffff", "#fff1b0"],
          alpha: [0, 1, 0],
          scale: [0.1, 0.45, 0.05],
          rotationSpeed: [-90, 90],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        particle: {
          shape: "ring",
          lifetime: 650,
          color: "#ffe27a",
          alpha: [0.85, 0],
          scale: [0.3, 2.4],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  shadowCurse: {
    duration: 700,
    emitters: [
      {
        burst: 30,
        radius: [60, 95],
        direction: "inward",
        speed: [60, 110],
        orbit: [100, 170],
        particle: {
          shape: "softCircle",
          lifetime: [480, 760],
          color: ["#c58bff", "#5a1e99"],
          alpha: [0, 0.85, 0],
          scale: [0.5, 0.15],
          blendMode: "add",
        },
      },
      {
        delay: 380,
        burst: 16,
        direction: "outward",
        radius: 6,
        speed: [30, 90],
        drag: 1.5,
        particle: {
          shape: "softCircle",
          lifetime: [600, 1050],
          color: ["#2a0f3d", "#0a0410"],
          alpha: [0.65, 0],
          scale: [0.6, 1.7],
          rotationSpeed: [-60, 60],
        },
      },
      {
        delay: 420,
        burst: 20,
        radius: 4,
        direction: "outward",
        speed: [160, 300],
        drag: 3,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [320, 620],
          color: ["#e8c4ff", "#7a2cff"],
          alpha: [1, 0],
          scale: [0.2, 0],
          blendMode: "add",
        },
      },
    ],
  },
  arcaneCharge: {
    duration: 900,
    emitters: [
      {
        rate: 48,
        radius: [55, 85],
        direction: "inward",
        speed: [70, 120],
        orbit: 180,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [480, 680],
          color: ["#b8f7ff", "#5a7dff"],
          alpha: [0, 1, 0.2],
          scale: [0.34, 0.1],
          blendMode: "add",
        },
      },
      {
        rate: 8,
        particle: {
          shape: "softCircle",
          lifetime: 500,
          color: "#8fdcff",
          alpha: [0, 0.5, 0],
          scale: [0.4, 1],
          blendMode: "add",
        },
      },
    ],
  },
  arcaneBurst: {
    duration: 420,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "flare",
          lifetime: 360,
          color: ["#ffffff", "#9fb6ff"],
          alpha: [1, 0],
          scale: [0.8, 2.6],
          rotationSpeed: 90,
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 30,
        radius: 4,
        direction: "outward",
        speed: [140, 300],
        drag: 2.5,
        orbit: [60, 120],
        particle: {
          shape: "star",
          lifetime: [420, 820],
          color: ["#e6f7ff", "#8a7dff", "#c86bff"],
          alpha: [1, 0],
          scale: [0.25, 0.05],
          rotationSpeed: [-240, 240],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        particle: {
          shape: "ring",
          lifetime: 420,
          color: "#a89bff",
          alpha: [0.9, 0],
          scale: [0.3, 2.8],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  teleport: {
    duration: 520,
    emitters: [
      {
        rate: 90,
        duration: 420,
        spreadX: 18,
        spreadY: 26,
        angle: -90,
        speed: [80, 220],
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [420, 720],
          color: ["#ffffff", "#9fd8ff", "#b26bff"],
          alpha: [0, 1, 0],
          scale: [0.32, 0.1],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        particle: {
          shape: "ring",
          lifetime: 480,
          color: "#bfe6ff",
          alpha: [0.9, 0],
          scale: [0.3, 2.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 320,
          color: "#e8f6ff",
          alpha: [0.9, 0],
          scale: [0.6, 1.8],
          blendMode: "add",
        },
      },
      {
        burst: 10,
        radius: [8, 40],
        angle: -90,
        speed: [20, 70],
        particle: {
          shape: "flare",
          lifetime: [400, 800],
          color: "#ffffff",
          alpha: [0, 1, 0],
          scale: [0.1, 0.35, 0.05],
          blendMode: "add",
        },
      },
    ],
  },
  poisonCloud: {
    duration: 720,
    emitters: [
      {
        rate: 30,
        duration: 700,
        spreadX: 28,
        spreadY: 8,
        angle: [-100, -80],
        speed: [20, 60],
        particle: {
          shape: "bubble",
          lifetime: [600, 1100],
          color: ["#d6ff9a", "#5fd13a"],
          alpha: [0, 0.9, 0],
          scale: [0.15, 0.4],
          blendMode: "add",
        },
      },
      {
        burst: 12,
        radius: [0, 16],
        direction: "outward",
        speed: [15, 45],
        particle: {
          shape: "softCircle",
          lifetime: [900, 1400],
          color: ["#8be04a", "#3b6b1a"],
          alpha: [0, 0.42, 0],
          scale: [0.7, 2],
          rotationSpeed: [-30, 30],
        },
      },
    ],
  },
  windCyclone: {
    duration: 700,
    emitters: [
      {
        rate: 70,
        duration: 600,
        radius: [10, 55],
        ellipse: 0.45,
        direction: "tangent",
        speed: [60, 120],
        orbit: [260, 360],
        gravity: -60,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [400, 700],
          color: ["#ffffff", "#bff5e0"],
          alpha: [0, 0.85, 0],
          scale: [0.34, 0.1],
          blendMode: "add",
        },
      },
      {
        burst: 14,
        radius: [0, 40],
        ellipse: 0.45,
        direction: "outward",
        speed: [30, 80],
        orbit: 180,
        particle: {
          shape: "softCircle",
          lifetime: [600, 1000],
          color: "#cfe9dc",
          alpha: [0, 0.3, 0],
          scale: [0.4, 1.3],
        },
      },
    ],
  },
  earthShatter: {
    duration: 400,
    emitters: [
      {
        burst: 18,
        spreadX: 16,
        angle: [-160, -20],
        speed: [180, 380],
        gravity: 900,
        particle: {
          shape: "square",
          lifetime: [520, 820],
          color: ["#b0946b", "#5c4a34"],
          alpha: [1, 1, 0],
          scale: [0.32, 0.18],
          rotationSpeed: [-540, 540],
        },
      },
      {
        burst: 16,
        spreadX: 20,
        angle: [-180, 0],
        speed: [30, 120],
        drag: 2,
        particle: {
          shape: "softCircle",
          lifetime: [600, 1100],
          color: "#9c8466",
          alpha: [0.45, 0],
          scale: [0.4, 1.7],
          rotationSpeed: [-40, 40],
        },
      },
      {
        burst: 1,
        particle: {
          shape: "ring",
          lifetime: 380,
          color: "#d9c3a0",
          alpha: [0.6, 0],
          scale: [0.4, 2.4],
          ease: "outCubic",
        },
      },
    ],
  },
  waterSplash: {
    duration: 400,
    emitters: [
      {
        burst: 24,
        spreadX: 8,
        angle: [-150, -30],
        speed: [150, 320],
        gravity: 820,
        particle: {
          shape: "circle",
          lifetime: [420, 720],
          color: ["#e6fbff", "#4aa3ff"],
          alpha: [1, 1, 0],
          scale: [0.16, 0.07],
          blendMode: "add",
        },
      },
      {
        burst: 1,
        burstCount: 2,
        burstInterval: 150,
        particle: {
          shape: "ring",
          lifetime: 520,
          color: "#bfeaff",
          alpha: [0.75, 0],
          scale: [0.3, 2.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 10,
        radius: [0, 14],
        direction: "outward",
        speed: [20, 60],
        particle: {
          shape: "softCircle",
          lifetime: [500, 900],
          color: "#d8f3ff",
          alpha: [0, 0.35, 0],
          scale: [0.4, 1.3],
          blendMode: "add",
        },
      },
    ],
  },
  criticalHit: {
    duration: 260,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 180,
          color: ["#ffffff", "#ffd36d"],
          alpha: [1, 0],
          scale: [0.6, 2.6],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 1,
        particle: {
          shape: "spark",
          lifetime: 240,
          rotation: 45,
          color: ["#ffffff", "#ffe08a"],
          alpha: [1, 0],
          scale: [2.6, 1.6],
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        burst: 1,
        particle: {
          shape: "spark",
          lifetime: 240,
          rotation: -45,
          color: ["#ffffff", "#ffe08a"],
          alpha: [1, 0],
          scale: [2.6, 1.6],
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        burst: 26,
        radius: 4,
        direction: "outward",
        speed: [200, 440],
        drag: 3.5,
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [180, 380],
          color: ["#ffffff", "#ff8a3d"],
          alpha: [1, 0],
          scale: [0.26, 0],
          blendMode: "add",
        },
      },
      {
        burst: 6,
        radius: [18, 40],
        particle: {
          shape: "flare",
          lifetime: [200, 420],
          color: "#fff4c2",
          alpha: [0, 1, 0],
          scale: [0.15, 0.5, 0.05],
          blendMode: "add",
        },
      },
    ],
  },
  manaRestore: {
    duration: 560,
    emitters: [
      {
        burst: 18,
        radius: [8, 26],
        ellipse: 0.5,
        angle: [-100, -80],
        speed: [30, 90],
        gravity: -20,
        particle: {
          shape: "flare",
          lifetime: [560, 1000],
          color: ["#e0f4ff", "#5aa8ff"],
          alpha: [0, 0.95, 0],
          scale: [0.2, 0.55, 0.1],
          rotationSpeed: [-120, 120],
          blendMode: "add",
        },
      },
      {
        rate: 30,
        duration: 480,
        radius: 26,
        innerRadius: 22,
        ellipse: 0.4,
        orbit: 220,
        angle: -90,
        speed: [20, 50],
        particle: {
          shape: "softCircle",
          lifetime: [500, 800],
          color: ["#9fd4ff", "#3a6bff"],
          alpha: [0, 0.6, 0],
          scale: [0.42, 0.16],
          blendMode: "add",
        },
      },
    ],
  },
  revive: {
    duration: 900,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 1000,
          color: "#fff4d6",
          alpha: [0, 0.7, 0],
          scale: [1, 3.4],
          blendMode: "add",
        },
      },
      {
        rate: 40,
        duration: 800,
        radius: 30,
        innerRadius: 26,
        ellipse: 0.4,
        orbit: 160,
        angle: -90,
        speed: [60, 120],
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [600, 1000],
          color: ["#ffffff", "#ffe89a"],
          alpha: [0, 1, 0],
          scale: [0.32, 0.1],
          blendMode: "add",
        },
      },
      {
        delay: 300,
        burst: 24,
        radius: [0, 30],
        angle: [-120, -60],
        speed: [40, 120],
        gravity: -30,
        particle: {
          shape: "star",
          lifetime: [700, 1200],
          color: ["#ffffff", "#ffd86b"],
          alpha: [1, 0],
          scale: [0.12, 0.45],
          rotationSpeed: [-180, 180],
          blendMode: "add",
        },
      },
    ],
  },
  meteorImpact: {
    duration: 520,
    emitters: [
      {
        burst: 1,
        particle: {
          shape: "softCircle",
          lifetime: 320,
          color: ["#ffffff", "#ff9a3c"],
          alpha: [1, 0],
          scale: [1.5, 5],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 40,
        radius: 10,
        direction: "outward",
        speed: [120, 320],
        drag: 2.2,
        gravity: -40,
        particle: {
          shape: "softCircle",
          lifetime: [420, 900],
          color: ["#fff1a6", "#ff6a1f", "#6d1d0c"],
          alpha: [1, 0.8, 0],
          scale: [0.6, 1.8],
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        burst: 26,
        spreadX: 20,
        angle: [-165, -15],
        speed: [220, 460],
        gravity: 900,
        particle: {
          shape: "square",
          lifetime: [600, 1000],
          color: ["#ffb35a", "#3a2a22"],
          alpha: [1, 1, 0],
          scale: [0.3, 0.16],
          rotationSpeed: [-600, 600],
        },
      },
      {
        burst: 1,
        particle: {
          shape: "ring",
          lifetime: 520,
          color: "#ffc27a",
          alpha: [0.9, 0],
          scale: [0.5, 4.2],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        delay: 180,
        burst: 18,
        radius: [0, 40],
        direction: "outward",
        speed: [20, 70],
        gravity: -25,
        particle: {
          shape: "softCircle",
          lifetime: [900, 1500],
          color: ["#4d4038", "#1f1a17"],
          alpha: [0, 0.45, 0],
          scale: [0.8, 2.4],
          rotationSpeed: [-40, 40],
        },
      },
    ],
  },
} satisfies Record<string, FxPreset>;

/**
 * Looping effects meant to stay attached to a character or a spot.
 * Use them with the `loop` prop.
 */
export const AURA_FX_PRESETS = {
  magicCircle: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 34,
        radius: 48,
        innerRadius: 46,
        ellipse: 0.45,
        orbit: 70,
        particle: {
          shape: "softCircle",
          lifetime: [900, 1400],
          color: ["#c9f8ff", "#4fa8ff"],
          alpha: [0, 0.9, 0],
          scale: [0.2, 0.42, 0.1],
          blendMode: "add",
        },
      },
      {
        loop: true,
        rate: 10,
        radius: [0, 44],
        ellipse: 0.45,
        angle: -90,
        speed: [12, 40],
        particle: {
          shape: "flare",
          lifetime: [800, 1400],
          color: ["#ffffff", "#8fd0ff"],
          alpha: [0, 0.9, 0],
          scale: [0.15, 0.4, 0.06],
          blendMode: "add",
        },
      },
    ],
  },
  powerAura: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 30,
        radius: 24,
        innerRadius: 16,
        ellipse: 0.4,
        angle: [-96, -84],
        speed: [40, 90],
        particle: {
          shape: "spark",
          align: "velocity",
          lifetime: [420, 760],
          color: ["#fff3a0", "#ff9d2e"],
          alpha: [0, 0.9, 0],
          scale: [0.4, 0.14],
          blendMode: "add",
        },
      },
      {
        loop: true,
        rate: 10,
        radius: 16,
        ellipse: 0.4,
        angle: -90,
        speed: [10, 30],
        particle: {
          shape: "softCircle",
          lifetime: [600, 1000],
          color: ["#ffd36d", "#ff6a1f"],
          alpha: [0, 0.35, 0],
          scale: [0.7, 1.5],
          blendMode: "add",
        },
      },
    ],
  },
  shieldBarrier: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 26,
        radius: 36,
        innerRadius: 34,
        orbit: 110,
        particle: {
          shape: "flare",
          lifetime: [700, 1100],
          color: ["#e6fbff", "#6fc8ff"],
          alpha: [0, 0.9, 0],
          scale: [0.18, 0.45, 0.1],
          blendMode: "add",
        },
      },
      {
        loop: true,
        rate: 1.4,
        particle: {
          shape: "ring",
          lifetime: 1100,
          color: "#8fd8ff",
          alpha: [0, 0.4, 0],
          scale: [2.4, 2.6],
          blendMode: "add",
        },
      },
    ],
  },
  summonPortal: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 60,
        radius: [40, 70],
        ellipse: 0.5,
        direction: "inward",
        speed: [20, 45],
        orbit: [150, 220],
        particle: {
          shape: "softCircle",
          lifetime: [700, 1100],
          color: ["#e0a8ff", "#8a3dff", "#2b0b5c"],
          alpha: [0, 0.8, 0],
          scale: [0.6, 0.2],
          blendMode: "add",
        },
      },
      {
        loop: true,
        rate: 6,
        particle: {
          shape: "softCircle",
          lifetime: 900,
          color: "#b67dff",
          alpha: [0, 0.45, 0],
          scale: [1, 2],
          blendMode: "add",
        },
      },
    ],
  },
  magicTrail: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 70,
        space: "world",
        spreadX: 3,
        spreadY: 3,
        speed: [0, 18],
        angle: [0, 360],
        particle: {
          shape: "softCircle",
          lifetime: [220, 420],
          color: ["#ffffff", "#8fd3ff", "#5b5bff"],
          alpha: [0.9, 0],
          scale: [0.6, 0],
          blendMode: "add",
        },
      },
      {
        loop: true,
        rate: 16,
        space: "world",
        spreadX: 6,
        spreadY: 6,
        speed: [10, 40],
        angle: [0, 360],
        particle: {
          shape: "flare",
          lifetime: [300, 600],
          color: "#dff2ff",
          alpha: [0, 1, 0],
          scale: [0.14, 0.35, 0.06],
          blendMode: "add",
        },
      },
    ],
  },
  fireTrail: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 60,
        space: "world",
        spreadX: 4,
        spreadY: 4,
        angle: [-110, -70],
        speed: [10, 40],
        particle: {
          shape: "softCircle",
          lifetime: [260, 520],
          color: ["#fff0a0", "#ff6a1f", "#8a1a0a"],
          alpha: [0.9, 0],
          scale: [0.5, 0.1],
          blendMode: "add",
        },
      },
      {
        loop: true,
        rate: 10,
        space: "world",
        angle: [-120, -60],
        speed: [20, 50],
        particle: {
          shape: "softCircle",
          lifetime: [500, 900],
          color: "#3f3a38",
          alpha: [0, 0.25, 0],
          scale: [0.3, 1],
        },
      },
    ],
  },
} satisfies Record<string, FxPreset>;

/** Looping RPG status markers (stun, poison, burn, freeze, sleep-like haze). */
export const STATUS_FX_PRESETS = {
  statusStun: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        burst: 3,
        burstInterval: 900,
        radius: 18,
        innerRadius: 18,
        ellipse: 0.35,
        orbit: 240,
        particle: {
          shape: "star",
          lifetime: 1100,
          color: ["#fff27a", "#ffd23a"],
          alpha: [0, 1, 1, 0],
          scale: 0.32,
          rotationSpeed: 180,
          blendMode: "add",
        },
      },
    ],
  },
  statusPoison: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        burst: 2,
        rate: 7,
        spreadX: 14,
        spreadY: 6,
        angle: [-100, -80],
        speed: [14, 34],
        particle: {
          shape: "bubble",
          lifetime: [700, 1200],
          color: ["#d6ff9a", "#62d43b"],
          alpha: [0, 0.9, 0],
          scale: [0.2, 0.42],
          blendMode: "add",
        },
      },
    ],
  },
  statusBurn: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 16,
        spreadX: 14,
        spreadY: 6,
        angle: [-100, -80],
        speed: [20, 50],
        particle: {
          shape: "flame",
          lifetime: [360, 640],
          color: ["#fff0a0", "#ff6a1f", "#b3200f"],
          alpha: [0, 0.9, 0],
          scale: [0.42, 0.12],
          blendMode: "add",
        },
      },
    ],
  },
  statusFreeze: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        burst: 2,
        rate: 6,
        spreadX: 16,
        spreadY: 18,
        particle: {
          shape: "flare",
          lifetime: [500, 900],
          color: ["#ffffff", "#9fe8ff"],
          alpha: [0, 1, 0],
          scale: [0.06, 0.26, 0.04],
          rotationSpeed: [-90, 90],
          blendMode: "add",
        },
      },
      {
        loop: true,
        rate: 4,
        spreadX: 14,
        angle: [60, 120],
        speed: [6, 18],
        particle: {
          shape: "softCircle",
          lifetime: [900, 1400],
          color: "#cdefff",
          alpha: [0, 0.3, 0],
          scale: [0.3, 0.9],
          blendMode: "add",
        },
      },
    ],
  },
  statusCurse: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        burst: 2,
        rate: 12,
        radius: 16,
        ellipse: 0.4,
        angle: [-100, -80],
        speed: [10, 30],
        orbit: 90,
        particle: {
          shape: "softCircle",
          lifetime: [700, 1100],
          color: ["#b36bff", "#2a0f3d"],
          alpha: [0, 0.6, 0],
          scale: [0.25, 0.6],
        },
      },
    ],
  },
} satisfies Record<string, FxPreset>;
