import type { FxPreset } from "./types";

export const FX_PRESETS = {
  hitSpark: {
    duration: 180,
    emitters: [
      {
        burst: 18,
        angle: [0, 360],
        speed: [120, 340],
        particle: {
          shape: "spark",
          lifetime: [160, 340],
          color: ["#fff4a8", "#ff7a2f"],
          alpha: [1, 0],
          scale: [0.18, 0],
          rotationSpeed: [-480, 480],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  slashSpark: {
    duration: 160,
    emitters: [
      {
        burst: 22,
        angle: [-12, 12],
        speed: [180, 430],
        spreadX: 10,
        spreadY: 3,
        particle: {
          shape: "spark",
          lifetime: [110, 260],
          color: ["#ffffff", "#ffcf5a"],
          alpha: [1, 0],
          scale: [0.16, 0],
          rotation: [-8, 8],
          rotationSpeed: [-260, 260],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 8,
        angle: [150, 210],
        speed: [60, 160],
        particle: {
          shape: "star",
          lifetime: [140, 320],
          color: ["#fff8cc", "#ff8f3d"],
          alpha: [0.85, 0],
          scale: [0.12, 0.4],
          blendMode: "add",
          ease: "outQuad",
        },
      },
    ],
  },
  impactBurst: {
    duration: 260,
    emitters: [
      {
        burst: 24,
        angle: [0, 360],
        speed: [130, 280],
        particle: {
          shape: "spark",
          lifetime: [180, 420],
          color: ["#fff3ba", "#d64d27"],
          alpha: [1, 0],
          scale: [0.2, 0],
          rotationSpeed: [-360, 360],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        burst: 10,
        angle: [0, 360],
        speed: [30, 90],
        particle: {
          shape: "softCircle",
          lifetime: [220, 520],
          color: ["#ffd18a", "#6d3a2a"],
          alpha: [0.38, 0],
          scale: [0.28, 1.15],
          ease: "outQuad",
        },
      },
    ],
  },
  smokePuff: {
    duration: 260,
    emitters: [
      {
        burst: 16,
        angle: [-130, -50],
        speed: [12, 58],
        spreadX: 10,
        spreadY: 6,
        gravity: -10,
        particle: {
          shape: "softCircle",
          lifetime: [520, 940],
          color: ["#8f8f8f", "#4f4f4f"],
          alpha: [0.38, 0],
          scale: [0.45, 1.85],
          rotationSpeed: [-40, 40],
          ease: "outQuad",
        },
      },
    ],
  },
  dustStep: {
    duration: 160,
    emitters: [
      {
        burst: 10,
        angle: [-170, -10],
        speed: [18, 86],
        spreadX: 8,
        spreadY: 3,
        particle: {
          shape: "softCircle",
          lifetime: [260, 520],
          color: "#b99a6a",
          alpha: [0.26, 0],
          scale: [0.22, 0.9],
          ease: "outQuad",
        },
      },
    ],
  },
  dashDust: {
    duration: 220,
    emitters: [
      {
        burst: 22,
        angle: [155, 205],
        speed: [70, 190],
        spreadX: 18,
        spreadY: 5,
        particle: {
          shape: "softCircle",
          lifetime: [300, 640],
          color: ["#cfb07c", "#8f744f"],
          alpha: [0.34, 0],
          scale: [0.28, 1.2],
          ease: "outCubic",
        },
      },
      {
        burst: 9,
        angle: [168, 192],
        speed: [150, 330],
        spreadX: 10,
        particle: {
          shape: "spark",
          lifetime: [120, 280],
          color: "#d9c08a",
          alpha: [0.42, 0],
          scale: [0.12, 0],
          ease: "outCubic",
        },
      },
    ],
  },
  magicBurst: {
    duration: 360,
    emitters: [
      {
        burst: 32,
        angle: [0, 360],
        speed: [70, 220],
        particle: {
          shape: "star",
          lifetime: [420, 840],
          color: ["#77e5ff", "#b970ff"],
          alpha: [0.95, 0],
          scale: [0.18, 0.75],
          rotationSpeed: [-220, 220],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  healPulse: {
    duration: 520,
    emitters: [
      {
        burst: 18,
        angle: [-120, -60],
        speed: [28, 86],
        spreadX: 20,
        spreadY: 10,
        gravity: -16,
        particle: {
          shape: "star",
          lifetime: [520, 980],
          color: ["#d9ffe6", "#55e68a"],
          alpha: [0.85, 0],
          scale: [0.18, 0.62],
          rotationSpeed: [-120, 120],
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        burst: 10,
        angle: [-105, -75],
        speed: [12, 42],
        spreadX: 16,
        particle: {
          shape: "softCircle",
          lifetime: [620, 1100],
          color: ["#9fffc5", "#3edc7c"],
          alpha: [0.3, 0],
          scale: [0.3, 1.0],
          blendMode: "add",
          ease: "outQuad",
        },
      },
    ],
  },
  campfire: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 38,
        angle: [-110, -70],
        speed: [16, 54],
        spreadX: 8,
        spreadY: 3,
        particle: {
          shape: "softCircle",
          lifetime: [360, 720],
          color: ["#ffd36d", "#ff4b1f"],
          alpha: [0.8, 0],
          scale: [0.25, 1.05],
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        loop: true,
        rate: 12,
        angle: [-115, -65],
        speed: [10, 30],
        particle: {
          shape: "softCircle",
          lifetime: [620, 1100],
          color: "#555555",
          alpha: [0.18, 0],
          scale: [0.35, 1.4],
          ease: "outQuad",
        },
      },
    ],
  },
  torchFire: {
    duration: 1000,
    emitters: [
      {
        loop: true,
        rate: 24,
        angle: [-104, -76],
        speed: [12, 42],
        spreadX: 4,
        spreadY: 2,
        particle: {
          shape: "softCircle",
          lifetime: [280, 560],
          color: ["#fff09a", "#ff5a22"],
          alpha: [0.75, 0],
          scale: [0.16, 0.72],
          blendMode: "add",
          ease: "outQuad",
        },
      },
      {
        loop: true,
        rate: 7,
        angle: [-112, -68],
        speed: [8, 26],
        particle: {
          shape: "softCircle",
          lifetime: [520, 960],
          color: "#4f4f4f",
          alpha: [0.13, 0],
          scale: [0.22, 0.9],
          ease: "outQuad",
        },
      },
    ],
  },
  pickup: {
    duration: 320,
    emitters: [
      {
        burst: 14,
        angle: [210, 330],
        speed: [70, 170],
        particle: {
          shape: "star",
          lifetime: [260, 620],
          color: ["#ffffff", "#ffe66d"],
          alpha: [1, 0],
          scale: [0.2, 0.65],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  levelUp: {
    duration: 820,
    emitters: [
      {
        burst: 30,
        angle: [-105, -75],
        speed: [80, 210],
        spreadX: 34,
        spreadY: 10,
        gravity: -24,
        particle: {
          shape: "star",
          lifetime: [620, 1180],
          color: ["#ffffff", "#ffe870"],
          alpha: [1, 0],
          scale: [0.16, 0.8],
          rotationSpeed: [-180, 180],
          blendMode: "add",
          ease: "outCubic",
        },
      },
      {
        duration: 420,
        rate: 36,
        angle: [-98, -82],
        speed: [90, 180],
        spreadX: 26,
        particle: {
          shape: "spark",
          lifetime: [420, 840],
          color: ["#fff8c8", "#66d9ff"],
          alpha: [0.75, 0],
          scale: [0.12, 0],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
  explosionSmall: {
    duration: 280,
    emitters: [
      {
        burst: 28,
        angle: [0, 360],
        speed: [120, 300],
        particle: {
          shape: "softCircle",
          lifetime: [300, 720],
          color: ["#fff1a6", "#d34b24"],
          alpha: [1, 0],
          scale: [0.25, 1.15],
          blendMode: "add",
          ease: "outCubic",
        },
      },
    ],
  },
} satisfies Record<string, FxPreset>;
